version: '2'
services:
    ccrawl-elasticsearch:
        container_name: ccrawl-elasticsearch
        image: elasticsearch:2.3.5
        # volumes:
        #     - ~/volumes/jhipster/CCrawl/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
